In [1]:
import pandas as pd

In [2]:
#loading results of YOLOv5 Detection
results = pd.read_csv('results.txt', header = None)
results

                                                     0
0    0 0.497596 0.371394 0.125 0.03125 0.391602 0_j...
1    0 0.450721 0.605769 0.189904 0.0817308 0.81787...
2    0 0.293269 0.311298 0.110577 0.0216346 0.41113...
3    0 0.44351 0.734375 0.252404 0.0793269 0.82666 ...
4    0 0.421875 0.740385 0.247596 0.0817308 0.80468...
..                                                 ...
144  0 0.426683 0.543269 0.127404 0.0480769 0.81201...
145  0 0.115385 0.742788 0.110577 0.144231 0.756836...
146  0 0.0204327 0.0961538 0.0360577 0.0961538 0.40...
147  0 0.52524 0.768029 0.204327 0.0600962 0.774902...
148  0 0.516827 0.463942 0.153846 0.0576923 0.83252...

[149 rows x 1 columns]

In [8]:
coor = []
for i in results[0]:
  a = i.split(' ')
  coor.append(a)

In [9]:
pd.DataFrame(coor)

     0          1  ...         5                                                6
0    0   0.497596  ...  0.391602    0_jpg.rf.101a25ecfaf7e38922107e9db1056326.txt
1    0   0.450721  ...  0.817871  100_jpg.rf.7cefc46f10af8ca02b75b18ecb39e823.txt
2    0   0.293269  ...  0.411133  101_jpg.rf.8abfd65df0049d2f6a8f948f58d6c3d9.txt
3    0    0.44351  ...   0.82666  102_jpg.rf.f8ffed56b9f9fda1cfc034f02a5de5e7.txt
4    0   0.421875  ...  0.804688  103_jpg.rf.2881ecc2e63860c0d944eb0e5a44ffd2.txt
..  ..        ...  ...       ...                                              ...
144  0   0.426683  ...  0.812012   97_jpg.rf.7ebe4ba4024a1fbc31df427100fea7e7.txt
145  0   0.115385  ...  0.756836   98_jpg.rf.3cb40d74344ddf95206e86f53f724e97.txt
146  0  0.0204327  ...  0.406006   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt
147  0    0.52524  ...  0.774902   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt
148  0   0.516827  ...   0.83252    9_jpg.rf.b78f756f360b75b3ddb8b21a6ac0c52f.txt

[149 rows x 7 columns]

In [10]:
df = pd.DataFrame()
df['center_x'] = pd.DataFrame(coor)[1]
df['center_y'] = pd.DataFrame(coor)[2]
df['width'] = pd.DataFrame(coor)[3]
df['height'] = pd.DataFrame(coor)[4]
df['confidence'] = pd.DataFrame(coor)[5]
df['filename'] = pd.DataFrame(coor)[6]
df

      center_x  ...                                         filename
0     0.497596  ...    0_jpg.rf.101a25ecfaf7e38922107e9db1056326.txt
1     0.450721  ...  100_jpg.rf.7cefc46f10af8ca02b75b18ecb39e823.txt
2     0.293269  ...  101_jpg.rf.8abfd65df0049d2f6a8f948f58d6c3d9.txt
3      0.44351  ...  102_jpg.rf.f8ffed56b9f9fda1cfc034f02a5de5e7.txt
4     0.421875  ...  103_jpg.rf.2881ecc2e63860c0d944eb0e5a44ffd2.txt
..         ...  ...                                              ...
144   0.426683  ...   97_jpg.rf.7ebe4ba4024a1fbc31df427100fea7e7.txt
145   0.115385  ...   98_jpg.rf.3cb40d74344ddf95206e86f53f724e97.txt
146  0.0204327  ...   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt
147    0.52524  ...   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt
148   0.516827  ...    9_jpg.rf.b78f756f360b75b3ddb8b21a6ac0c52f.txt

[149 rows x 6 columns]

In [11]:
dict(df.iloc[0])

{'center_x': '0.497596',
 'center_y': '0.371394',
 'confidence': '0.391602',
 'filename': '0_jpg.rf.101a25ecfaf7e38922107e9db1056326.txt',
 'height': '0.03125',
 'width': '0.125'}

In [12]:
def del_element(dict):
  del dict['filename']
  return dict

In [13]:
relative_coordinates = pd.Series(dict(del_element(df.iloc[i])) for i in range(len(df)))
relative_coordinates

0      {'center_x': '0.497596', 'center_y': '0.371394...
1      {'center_x': '0.450721', 'center_y': '0.605769...
2      {'center_x': '0.293269', 'center_y': '0.311298...
3      {'center_x': '0.44351', 'center_y': '0.734375'...
4      {'center_x': '0.421875', 'center_y': '0.740385...
                             ...
144    {'center_x': '0.426683', 'center_y': '0.543269...
145    {'center_x': '0.115385', 'center_y': '0.742788...
146    {'center_x': '0.0204327', 'center_y': '0.09615...
147    {'center_x': '0.52524', 'center_y': '0.768029'...
148    {'center_x': '0.516827', 'center_y': '0.463942...
Length: 149, dtype: object

In [14]:
relative_coordinates[0]

{'center_x': '0.497596',
 'center_y': '0.371394',
 'confidence': '0.391602',
 'height': '0.03125',
 'width': '0.125'}

In [15]:
df['relative_coordinates'] = relative_coordinates
df.drop(['center_x', 'center_y', 'width', 'height', 'confidence'], inplace=True, axis=1)

In [16]:
df

                                            filename                               relative_coordinates
0      0_jpg.rf.101a25ecfaf7e38922107e9db1056326.txt  {'center_x': '0.497596', 'center_y': '0.371394...
1    100_jpg.rf.7cefc46f10af8ca02b75b18ecb39e823.txt  {'center_x': '0.450721', 'center_y': '0.605769...
2    101_jpg.rf.8abfd65df0049d2f6a8f948f58d6c3d9.txt  {'center_x': '0.293269', 'center_y': '0.311298...
3    102_jpg.rf.f8ffed56b9f9fda1cfc034f02a5de5e7.txt  {'center_x': '0.44351', 'center_y': '0.734375'...
4    103_jpg.rf.2881ecc2e63860c0d944eb0e5a44ffd2.txt  {'center_x': '0.421875', 'center_y': '0.740385...
..                                               ...                                                ...
144   97_jpg.rf.7ebe4ba4024a1fbc31df427100fea7e7.txt  {'center_x': '0.426683', 'center_y': '0.543269...
145   98_jpg.rf.3cb40d74344ddf95206e86f53f724e97.txt  {'center_x': '0.115385', 'center_y': '0.742788...
146   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt  {'center_x': '0.0204327', 'center_y': '0.09615...
147   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt  {'center_x': '0.52524', 'center_y': '0.768029'...
148    9_jpg.rf.b78f756f360b75b3ddb8b21a6ac0c52f.txt  {'center_x': '0.516827', 'center_y': '0.463942...

[149 rows x 2 columns]

In [17]:
data=df

In [18]:
def details(x,flag_2):
        wid=float(x['width'])/2.0
        hi=float(x['height'])/2.0
        if flag_2=='y2':
            return float(x['center_y'])+hi
        if flag_2=='x2':
            return float(x['center_x'])+wid
        if flag_2=='x1':
            return float(x['center_x'])-wid
        if flag_2=='y1':
            return float(x['center_y'])-hi
data['x1']=data['relative_coordinates'].transform(lambda f:details(f,'x1'))    
data['y1']=data['relative_coordinates'].transform(lambda f:details(f,'y1'))  
data['x2']=data['relative_coordinates'].transform(lambda f:details(f,'x2'))  
data['y2']=data['relative_coordinates'].transform(lambda f:details(f,'y2'))

In [19]:
data

                                            filename  ...        y2
0      0_jpg.rf.101a25ecfaf7e38922107e9db1056326.txt  ...  0.387019
1    100_jpg.rf.7cefc46f10af8ca02b75b18ecb39e823.txt  ...  0.646634
2    101_jpg.rf.8abfd65df0049d2f6a8f948f58d6c3d9.txt  ...  0.322115
3    102_jpg.rf.f8ffed56b9f9fda1cfc034f02a5de5e7.txt  ...  0.774038
4    103_jpg.rf.2881ecc2e63860c0d944eb0e5a44ffd2.txt  ...  0.781250
..                                               ...  ...       ...
144   97_jpg.rf.7ebe4ba4024a1fbc31df427100fea7e7.txt  ...  0.567307
145   98_jpg.rf.3cb40d74344ddf95206e86f53f724e97.txt  ...  0.814904
146   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt  ...  0.144231
147   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.txt  ...  0.798077
148    9_jpg.rf.b78f756f360b75b3ddb8b21a6ac0c52f.txt  ...  0.492788

[149 rows x 6 columns]

In [20]:
count = 0
for i in df['filename']:
  data['filename'].iloc[count] = i.replace("txt", "jpg")
  count += 1

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [21]:
data

                                            filename  ...        y2
0      0_jpg.rf.101a25ecfaf7e38922107e9db1056326.jpg  ...  0.387019
1    100_jpg.rf.7cefc46f10af8ca02b75b18ecb39e823.jpg  ...  0.646634
2    101_jpg.rf.8abfd65df0049d2f6a8f948f58d6c3d9.jpg  ...  0.322115
3    102_jpg.rf.f8ffed56b9f9fda1cfc034f02a5de5e7.jpg  ...  0.774038
4    103_jpg.rf.2881ecc2e63860c0d944eb0e5a44ffd2.jpg  ...  0.781250
..                                               ...  ...       ...
144   97_jpg.rf.7ebe4ba4024a1fbc31df427100fea7e7.jpg  ...  0.567307
145   98_jpg.rf.3cb40d74344ddf95206e86f53f724e97.jpg  ...  0.814904
146   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.jpg  ...  0.144231
147   99_jpg.rf.c9924734269f0df9f625593dce1e72e4.jpg  ...  0.798077
148    9_jpg.rf.b78f756f360b75b3ddb8b21a6ac0c52f.jpg  ...  0.492788

[149 rows x 6 columns]

In [ ]:
!wget valid_dataset

In [ ]:
!unzip valid_dataset -d anpr_dataset/

In [24]:
!mkdir -p 'anpr_dataset/valid_cropped'

In [25]:
from PIL import Image
count=0
for x,y in data.iterrows():
  img = Image.open('/content/anpr_dataset/valid/images/'+str(y['filename']))
  dim=img.size
  w,h=dim[0],dim[1]
  x1=y['x1']*w
  x2=y['x2']*w
  y1=y['y1']*h
  y2=y['y2']*h
  area=(x1,y1,x2,y2)
  print(count)
  cropped_img = img.crop(area)
  cropped_img=cropped_img.convert('RGB')
  cropped_img.save("anpr_dataset/valid_cropped/"+str(x)+'.jpg')
  count+=1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148

In [27]:
#%cp -r anpr_dataset/valid_cropped /content/drive/MyDrive/anpr/